import { Inject, Injectable } from '@angular/core';
import { UserAuthService } from './userauth.service';
import { LanguageService } from './language-service.service';
import { CurrencyService } from './currency.service';
import { Store, select } from '@ngrx/store';
import { AppState } from '../../../storage/app.state';
import { DOCUMENT } from '@angular/common';
import { selectStoreColors } from '../../../storage/state/state.selectors';
import { filter } from 'rxjs';
import { setAccountSelect, setAccounts, setClientSelect, setConfiguration, setFiveColor, setFourColor, setMenu, setPrimaryColor, setRecipientSelect, setRecipients, setSecondaryColor, setSevenColor, setSixColor, setThirdColor, setUnitLength, setUnitVolume, setUnitWeight } from '../../../storage/state/state.actions';
import { StoreConfigurationService } from '../../../graphql/services/store-configurations/store-configurations.service';
import { setConfigurations } from '../../model/config/config.model';
import { StoreConfigurationsResponse } from '../../../graphql/models/store-configurations/store-configurations.model';
import { AccountService } from '../../../graphql/services/account/account.service';
import { ProgreesBarService } from './progrees-bar.service';
import { Router } from '@angular/router';

@Injectable({
  providedIn: 'root'
})
export class StoreConfigurationsService {

  private configurationStoreValue!:any;

  constructor(
    private userAuthService: UserAuthService,
    private languageService: LanguageService,
    private currencyService: CurrencyService,
    private store: Store<AppState>,
    @Inject(DOCUMENT) private document: Document,
    private storeConfigurationsService: StoreConfigurationService,
    private accountService: AccountService,
    private progreesBarService:ProgreesBarService,
    private router: Router
  ) { }


  public data = {
	
    "ConfigurationStore": [
        {
            "StoreName": "Adage - Cemento",
            "MeasurementUnitsDecimalSeparator": ",",
            "MeasurementUnitsDecimalPlaces": "0",
            "CurrencyDecimalSeparator": ",",
            "LengthUnitsDecimalSeparator": ",",
            "LengthUnitsDecimalPlaces": "0",
            "CurrencyDecimalPlaces": "0",
            "StoreImage": "https://stcolmcfsqa001.blob.core.windows.net/standalone/iconStore/logosimbolo%20adage%20azul.svg",
            "LanguageTemplate": "https://stcolmcfsqa001.blob.core.windows.net/standalone/lenguageStore/EnglishTemplate %281%29.json",
            "VolumenIdentifier": "mL",
            "MesuIdentifier": "lb",
            "languageIdentifier": "EN",
            "DateFormatIdentifier": "DMY",
            "CurrenceIdentifier": "USD",
            "VolumeUnitsName": "Mililitro",
            "__typename": "ConfigurationStoreEntity"
        }
    ],
    "Menu": [
        {
            "Label": "Inicio",
            "IconClass": "home-icon-menu",
            "RouterLink": "/external/home",
            "ShowInCenterMenu": true,
            "CenterMenuImageUrl": "url-2",
            "CenterMenuAdditionalText": null,
            "__typename": "MenuEntity"
        },
        {
            "Label": "Toma de pedido",
            "IconClass": "cart-icon-menu",
            "RouterLink": "/external/placeorder",
            "ShowInCenterMenu": true,
            "CenterMenuImageUrl": "url-1",
            "CenterMenuAdditionalText": "additional-text-1",
            "__typename": "MenuEntity"
        },
        {
            "Label": "Consulta de pedido",
            "IconClass": "orders-icon-menu",
            "RouterLink": "/external/yourorder",
            "ShowInCenterMenu": true,
            "CenterMenuImageUrl": "url-2",
            "CenterMenuAdditionalText": "additional-text-2",
            "__typename": "MenuEntity"
        },
        {
            "Label": "Mi Perfil",
            "IconClass": "myprofile-icon-menu",
            "RouterLink": "/external/myprofile",
            "ShowInCenterMenu": true,
            "CenterMenuImageUrl": "url-2",
            "CenterMenuAdditionalText": null,
            "__typename": "MenuEntity"
        },
        {
            "Label": "Contactenos",
            "IconClass": "contactus-icon-menu",
            "RouterLink": "/external/contactus/",
            "ShowInCenterMenu": true,
            "CenterMenuImageUrl": "url-2",
            "CenterMenuAdditionalText": null,
            "__typename": "MenuEntity"
        }
    ],
    "StyleType": [
        {
            "StyleTypeName": "OneColor",
            "StyleValue": "#3182CE",
            "StyleTypeDescription": "Utilizado en botones de acción principales",
            "__typename": "StyleTypeEntity"
        },
        {
            "StyleTypeName": "TwoColor",
            "StyleValue": "#2B6CB0",
            "StyleTypeDescription": "Utilizado en botones de acción secundarios.",
            "__typename": "StyleTypeEntity"
        },
        {
            "StyleTypeName": "ThreeColor",
            "StyleValue": "#1A202C",
            "StyleTypeDescription": "Utilizado en títulos, como indicador de opción seleccionada en el menú",
            "__typename": "StyleTypeEntity"
        },
        {
            "StyleTypeName": "FourColor",
            "StyleValue": "#3182CE",
            "StyleTypeDescription": "Utilizado en alertas",
            "__typename": "StyleTypeEntity"
        },
        {
            "StyleTypeName": "FontColor",
            "StyleValue": "#1A202C",
            "StyleTypeDescription": "Color fuentes",
            "__typename": "StyleTypeEntity"
        },
        {
            "StyleTypeName": "FontButtonColor",
            "StyleValue": "#ffffff",
            "StyleTypeDescription": "Color fuentes de botones",
            "__typename": "StyleTypeEntity"
        }
    ],
    "FindClient": {
        "client": {
            "ClientId": 32,
            "AccountId": 32,
            "RecipientId": 37,
            "FiscalId": "860852321",
            "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
            "BusinessId": 1,
            "SegmentId": "51",
            "SubSegmentId": 1,
            "AccountName": "HOMECENTER TIENDA PRUEBA 20240531",
            "AccountActive": true,
            "AccountActiveName": "ACTIVO",
            "ZoneId": "CEN",
            "SubZoneId": 1,
            "OriginId": 1,
            "Address": "DIRECCION CLIENTE 34",
            "ZonesName": "CENTRO",
            "SubZonesName": "SUBZONA 1",
            "OriginName": "Planta occidente",
            "ZipCode": "050001",
            "Latitude": "6.25184",
            "Longitude": "-75.56359",
            "ClientActive": true,
            "ClientActiveName": "ACTIVO",
            "BusinessName": "Masivo",
            "SegmentName": "GRIS",
            "SubSegmentName": "CONSTRUCTOR",
            "DeliveryTypeId": 1,
            "DeliveryTypeName": "Entrega",
            "PaymentConditionId": "C01",
            "PaymentConditionName": "Crédito 1 Dia",
            "DownloadTypeId": 1,
            "DownloadName": "Sin descargue",
            "IsPurchaseOrderRequired": true,
            "RecipientActive": true,
            "RecipientActiveName": "ACTIVO",
            "PhoneNumber": "5013187654323",
            "TechnicalAvisorId": 2,
            "SaleAdvisorsId": 1,
            "TechnicalAvisorName": "Juan carlos tobon",
            "TechnicalAvisorEmail": "carlos@gmail.com",
            "SaleAdvisorsName": "Karen ortega",
            "SaleAdvisorsEmail": "karen@gmail.com",
            "ClientProfileId": 34,
            "LocationProfileId": 40,
            "RecipientProfileId": 40,
            "ClientServiceProfileId": 40,
            "AddressDetails": null,
            "__typename": "Client"
        },
        "accounts": [
            {
                "ClientId": 26,
                "AccountId": 32,
                "RecipientId": 37,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 38,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 39,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 40,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 41,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 42,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 43,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 44,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 45,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 46,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 47,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 48,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 34,
                "RecipientId": 49,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 50,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 51,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 52,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 53,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 54,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 55,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 56,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 57,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 58,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 35,
                "RecipientId": 59,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 60,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 61,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 62,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 63,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 64,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 65,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 66,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 67,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 68,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            },
            {
                "ClientId": 26,
                "AccountId": 36,
                "RecipientId": 69,
                "FiscalId": "860852327",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "EASY CIUDAD SALITRE",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": true,
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 40,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "AccountFilteredByStoreId"
            }
        ],
        "recipientDefault": [
            {
                "ClientId": 32,
                "AccountId": 32,
                "RecipientId": 37,
                "FiscalId": "860852321",
                "ClientName": "HOMECENTER TIENDA PRUEBA 20240531",
                "BusinessId": 1,
                "SegmentId": "51",
                "SubSegmentId": 1,
                "AccountName": "HOMECENTER TIENDA PRUEBA 20240531",
                "AccountActive": true,
                "AccountActiveName": "ACTIVO",
                "ZoneId": "CEN",
                "SubZoneId": 1,
                "OriginId": 1,
                "Address": "DIRECCION CLIENTE 34",
                "ZonesName": "CENTRO",
                "SubZonesName": "SUBZONA 1",
                "OriginName": "Planta occidente",
                "ZipCode": "050001",
                "Latitude": "6.25184",
                "Longitude": "-75.56359",
                "ClientActive": true,
                "ClientActiveName": "ACTIVO",
                "BusinessName": "Masivo",
                "SegmentName": "GRIS",
                "SubSegmentName": "CONSTRUCTOR",
                "DeliveryTypeId": 1,
                "DeliveryTypeName": "Entrega",
                "PaymentConditionId": "C01",
                "PaymentConditionName": "Crédito 1 Dia",
                "DownloadTypeId": 1,
                "DownloadName": "Sin descargue",
                "IsPurchaseOrderRequired": "true",
                "RecipientActive": true,
                "RecipientActiveName": "ACTIVO",
                "PhoneNumber": "5013187654323",
                "TechnicalAvisorId": 2,
                "SaleAdvisorsId": 1,
                "TechnicalAvisorName": "Juan carlos tobon",
                "TechnicalAvisorEmail": "carlos@gmail.com",
                "SaleAdvisorsName": "Karen ortega",
                "SaleAdvisorsEmail": "karen@gmail.com",
                "ClientProfileId": 34,
                "LocationProfileId": 40,
                "RecipientProfileId": 40,
                "ClientServiceProfileId": 40,
                "AddressDetails": null,
                "__typename": "RecipientEntity"
            }
        ],
        "__typename": "ListClientsAccounts"
    }
};


  public getStoreConfigurations() {
    this.progreesBarService.showProgressBar();
    this.progreesBarService.showLoadInitial();

    // this.storeConfigurationsService.getStoreConfigurations().subscribe(resp => {
    //   this.configurationStoreValue = resp;
    //   this.setStoreConfigurations();
    //   this.progreesBarService.hideProgressBar();
    //   this.progreesBarService.hideLoadInitial();
    //   this.router.navigate(['/external/home']);
    // });

      this.configurationStoreValue = this.data;
      this.setStoreConfigurations();
      this.progreesBarService.hideProgressBar();
      this.progreesBarService.hideLoadInitial();
      this.router.navigate(['/external/home']);
  }

  public setStoreConfigurations() {
    this.userAuthService.dispatch();
    this.dispatchConfiguration();
    this.dispatchMenu();
    this.dispatchClient();
    this.dispatchAccounts();
    this.userAuthService.setDefaultUser();
    this.languageService.initialize();
    this.setColorStore();
  }

  public dispatchMenu() {
    this.store.dispatch(setMenu({ menu: this.configurationStoreValue.Menu}));
  }

  public dispatchClient() {
    this.store.dispatch(setClientSelect({ clientSelect: this.configurationStoreValue.FindClient.client}));
  }

  public dispatchAccounts() {
    this.store.dispatch(setAccounts({ accounts: this.configurationStoreValue.FindClient.accounts}));
    this.store.dispatch(setAccountSelect({ accountSelect: this.configurationStoreValue.FindClient.accounts[0]}));
    this.store.dispatch(setRecipientSelect({ recipientSelect: this.configurationStoreValue.FindClient.recipientDefault[0] }));
    this.store.dispatch(setRecipients({ recipients: this.configurationStoreValue.FindClient.recipientDefault }));
  }

  public dispatchConfiguration() {
    this.store.dispatch(setConfiguration({ configuration: setConfigurations(this.configurationStoreValue)}));
  }


  public setColorStore() {
    this.store.pipe(select(selectStoreColors),
      filter((curreny: any) => curreny !== undefined)
    ).subscribe((configColors) => {
      if (typeof this.document !== 'undefined') {
        this.document.documentElement.style.setProperty('--primary-color', configColors.primary);
        this.document.documentElement.style.setProperty('--secondary-color', configColors.secondary);
        this.document.documentElement.style.setProperty('--titles-color', configColors.titles);
        this.document.documentElement.style.setProperty('--alerts-color', configColors.alerts);
        this.document.documentElement.style.setProperty('--bodyFont-color', configColors.bodyFont);
        this.document.documentElement.style.setProperty('--buttonsFont-color', configColors.buttonsFont);
        this.document.documentElement.style.setProperty('--borderHighlight-color', configColors.highlightColor);
      }
    });
  }

  onChangeLanguage(selectedLanguage: string): void {
    if(selectedLanguage) {
      this.languageService.updateLanguage(selectedLanguage);
    }
  }

  onChangeCurrency(selectedCurrency: string): void {
    if(selectedCurrency) {
      this.currencyService.updateCurrency(selectedCurrency);
    }
  }

  onChangeLengthUnit(selectedLength: string): void {
    if(selectedLength) {
      this.store.dispatch(setUnitLength({ selectedLengthUnit: selectedLength }));
    }
  }

  onChangeWeightUnit(selectedWeight: string): void {
    if(selectedWeight) {
      this.store.dispatch(setUnitWeight({ selectedWeighthUnit: selectedWeight }));
    }
  }

  onChangeVolumeUnit(selectedVolume: string): void {
    if(selectedVolume) {
      this.store.dispatch(setUnitVolume({ selectedVolumeUnit: selectedVolume }));
    }
  }

  onColorChange(event: any, type: string) {

    switch (type) {
      case 'one':
        this.store.dispatch(setPrimaryColor({ primary: event.value }));
        break;
      case 'two':
        this.store.dispatch(setSecondaryColor({ secondary: event.value }));
        break;
      case 'three':
        this.store.dispatch(setThirdColor({ titles : event.value }));
        break;
      case 'four':
        this.store.dispatch(setFourColor({ alerts: event.value }));
        break;
      case 'five':
        this.store.dispatch(setFiveColor({ bodyFont: event.value }));
        break;
      case 'six':
        this.store.dispatch(setSixColor({ buttonsFont: event.value }));
        break;
      case 'seven':
        this.store.dispatch(setSevenColor({ seventhColor: event.value }));
        break;
      default:
        break;
    }
  }

  
}
